artifacts_root: artifacts

data_root: 
  source: https://download.microsoft.com/download/3/E/1/3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip
  local_storage_dir: ../data_root_dvc/

data_ingestion:
  root_dir: DataIngestion
  train: train
  test: test